name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: |
          npm install @semantic-release/commit-analyzer \
                      @semantic-release/release-notes-generator \
                      @semantic-release/github \
                      conventional-changelog-eslint \
                      semantic-release
      - name: Create Release
        run: |
          npx semantic-release -e ./.github/.releaserc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
